// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// setup
void setup();
RcppExport SEXP poster_setup() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    setup();
    return R_NilValue;
END_RCPP
}
// end
void end();
RcppExport SEXP poster_end() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    end();
    return R_NilValue;
END_RCPP
}
// normalise_addr
CharacterVector normalise_addr(CharacterVector addresses);
RcppExport SEXP poster_normalise_addr(SEXP addressesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type addresses(addressesSEXP);
    __result = Rcpp::wrap(normalise_addr(addresses));
    return __result;
END_RCPP
}
// parse_addr
DataFrame parse_addr(CharacterVector addresses);
RcppExport SEXP poster_parse_addr(SEXP addressesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type addresses(addressesSEXP);
    __result = Rcpp::wrap(parse_addr(addresses));
    return __result;
END_RCPP
}
