# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setup <- function() {
    invisible(.Call('poster_setup', PACKAGE = 'poster'))
}

end <- function() {
    invisible(.Call('poster_end', PACKAGE = 'poster'))
}

#'@title Normalise postal addresses
#'@description \code{\link{normalise_addr}} takes street
#'addresses and normalises them within the context of a specific
#'country or language. It currently recognises 60 different locales.
#'
#'@param addresses a character vector of addresses to normalise
#'
#'@return a character vector of normalised addresses.
#'
#'@examples
#'# Normalise an English address!
#'normalise_addr("fourty seven love lane pinner")
#'# [1] "47 love lane pinner"
#'
#'# Normalise a French one
#'normalise_addr("Quatre-vignt-douze Ave des Champs-Élysées")
#'# "92 avenue des champs-elysees"
#'
#'@seealso \code{\link{parse_addr}} for parsing addresses.
#'@export
normalise_addr <- function(addresses) {
    .Call('poster_normalise_addr', PACKAGE = 'poster', addresses)
}

parse_addr <- function(addresses) {
    .Call('poster_parse_addr', PACKAGE = 'poster', addresses)
}

